export enum EventStoreEventName {
  JOB_CREATED_EVENT = 'JOB_CREATED_EVENT',
  STEP_PROCESSED_EVENT = 'STEP_PROCESSED_EVENT',
  TASK_FOO_EXECUTED_EVENT = 'TASK_FOO_EXECUTED_EVENT',
  TASK_QUX_EXECUTED_EVENT = 'TASK_QUX_EXECUTED_EVENT',
  TASK_BAR_EXECUTED_EVENT = 'TASK_BAR_EXECUTED_EVENT',
  ALL_TASKS_COMPLETED_EVENT = 'ALL_TASKS_COMPLETED_EVENT',
  JOB_FINALIZED_EVENT = 'JOB_FINALIZED_EVENT',
}
